# Main method for this program.

cc_binary(
    name = "collect_sweeps_main",
    srcs = ["collect_sweeps_main.cc"],
    deps = [
        "//rplidar_lib:rplidar",
        "//rplidar_lib:rplidar_driver",
    ],
)
