package(default_visibility = ["//visibility:public"])

cc_library(
    name = "win_functions",
    srcs = ["win_functions.h"],
)

cc_library(
    name = "commandlineflags",
    srcs = ["commandlineflags.h"],
)
