# Protocol Buffers for RPLidar 3D.
package(default_visibility = ["//visibility:public"])

proto_library(
    name = "lidar_scan_proto",
    srcs = ["lidar_scan.proto"],
    deps = [],
)

cc_proto_library(
    name = "lidar_scan_cc_proto",
    deps = [":lidar_scan_proto"],
)
